### ISSUE TITLE
Loop Detection? Localization Mode?

### ISSUE THREAD

**Issue by tyutyuginslava** [JakobEngel/dso#10]
Hello! Good job!
Your algorithm makes Loop Detection? Localization Mode?

**Comment by JakobEngel** [comment]
No, DSO is a pure visual odometry, without any loop-closure detection / re-localization / global map optimization. 
I believe all those things are possible in the DSO framework (in some cases similar to how it's done in LSD-SLAM, in some cases some more research is required), however - since I finished my PhD - I will probably not be the one implementing / developing those things.
