### ISSUE TITLE
Compiling DSO on ARM processor

### ISSUE THREAD

**Issue by sunghoon031** [JakobEngel/dso#31]
I found that you use SSE optimization, which is not supported in ARM devices...

Do you have any ideas/suggestions for workaround if I would like to compile it on ARM devices (e.g. Odroid)? 

BTW, Thank a lot for sharing your source code! It's super cool !! :+1:

**Comment by JakobEngel** [comment]
Yes - I removed the respective non-SSE versions of the functions where SSE is used,
 since I didn't want to always have to maintain / adapt two versions during development.
However, it should be fairly straight-forward to re-introduce them, especially since SSE is only
used in a fairly limited set of functions.
If you need the performance (in particular for the CoarseTracker, where it is probably most relevant), you can use NEON instead.

**Comment by hwiryong-jung** [comment]
On NVIDIA's TX1, same issue exists.. (it's also ARM processor : (|).....  )

**Comment by adroit91** [comment]
Hi,

I have successfully been able to use it by wrapping with:
https://github.com/jratcliff63367/sse2neon

**Comment by israelshirk** [comment]
Repeat from #57: Here's a site with some info on converting the Intel SSE instructions to ARM NEON instructions: http://codesuppository.blogspot.com/2015/02/sse2neonh-porting-guide-and-header-file.html, which is referenced above by @adroit91 for the source code only.

I'll likely throw an automated script to do this translation for me in the next day or two, but it's easy enough off the blog post and source.
