### ISSUE TITLE
Adding More docs and/or Doxygen

### ISSUE THREAD

**Issue by mah92** [JakobEngel/dso#33]
Hi, I really appreciate your work, and the good willing behind sharing it.
If you like more people use your code, you may like to add more description about how the code is written, files, functions, variables, etc...
I had some questions and don't know if it is the write place to ask them.
You can add answers to these questions to somewhere in docs or in doxygen.
If you like I am also ready to help writing the Doxygen doc...

**Comment by NikolausDemmel** [comment]
More documentation would be nice, yes, but this will very likely not happen in a systematic way due to lack of time. Maybe over time and in possible future iterations or forks by other people.

Closing this issue. Questions about the code can be asked in issues. You just have to hope someone that knows reads it and has time to answer.
