### ISSUE TITLE
Confused  about ‘rotDelta’

### ISSUE THREAD

**Issue by slowplayer** [JakobEngel/dso#46]
in src/FullSystem/FullSystem.cpp,line 315
`for(float rotDelta=0.02; rotDelta < 0.05; rotDelta++)`,
and I changed that to `for(float rotDelta=0.02; rotDelta < 0.05; rotDelta+=0.01)`,
then ran the same image  sequence twice，the two spent similar time.But,the latter has more possibilities.
I wanna know what the moviation you choose the former.thanks

**Comment by JakobEngel** [comment]
indeed it should probably be something like `rotDelta+=0.01` or `rotDelta+=0.02`, otherwise the loop does not make much sense... thanks!

That loop is only relevant when tracking fails with the default initialisation (constant motion assumption), which corresponds to the first entry pushed into `lastF_2_fh_tries` (i.e., direct image alignment with the reference frame, `trackNewestCoarse`, returns false). This almost never happens (probably it does not happen at all in the sequence you tried).... you can consider it a sort of a Hail Mary attempt at recovering, by trying a bunch of different initializations, rather than giving up and getting lost completely.
DSO will always give a warning on the command line if this happens (`RE-TRACK ATTEMPT %d with initOption %d [...]`).
